services:
  web:
    image: web
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres-database;Database=test_database;User Id=admin;Password=admin;Port=5432"
    depends_on:
      - postgres
    ports:
      - "81:8080"
      - "444:8081"
    networks:
      - front-tier
      - back-tier
  webuiblazor:
    image: webuiblazor
    build:
      context: .
      dockerfile: src/WebUIBlazor/Dockerfile
    environment:
      ApiAddress: "http://web:8080/api/"
    depends_on:
      - web
    ports:
      - "80:8080"
      - "443:8081"
    networks:
      - front-tier
  postgres:
    container_name: postgres-database
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_DB: "test_database"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    networks:
      - back-tier


networks:
  front-tier:
    name: front-tier
    driver: bridge
  back-tier:
    name: back-tier
    driver: bridge
